// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_msg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_msg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_msg_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_msg_2eproto;
class PlayerLoginMsg;
struct PlayerLoginMsgDefaultTypeInternal;
extern PlayerLoginMsgDefaultTypeInternal _PlayerLoginMsg_default_instance_;
class ServerRespondMsg;
struct ServerRespondMsgDefaultTypeInternal;
extern ServerRespondMsgDefaultTypeInternal _ServerRespondMsg_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::PlayerLoginMsg* Arena::CreateMaybeMessage<::PlayerLoginMsg>(Arena*);
template<> ::ServerRespondMsg* Arena::CreateMaybeMessage<::ServerRespondMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class PlayerLoginMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PlayerLoginMsg) */ {
 public:
  inline PlayerLoginMsg() : PlayerLoginMsg(nullptr) {}
  ~PlayerLoginMsg() override;
  explicit PROTOBUF_CONSTEXPR PlayerLoginMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PlayerLoginMsg(const PlayerLoginMsg& from);
  PlayerLoginMsg(PlayerLoginMsg&& from) noexcept
    : PlayerLoginMsg() {
    *this = ::std::move(from);
  }

  inline PlayerLoginMsg& operator=(const PlayerLoginMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerLoginMsg& operator=(PlayerLoginMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerLoginMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerLoginMsg* internal_default_instance() {
    return reinterpret_cast<const PlayerLoginMsg*>(
               &_PlayerLoginMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PlayerLoginMsg& a, PlayerLoginMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(PlayerLoginMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerLoginMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerLoginMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PlayerLoginMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PlayerLoginMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const PlayerLoginMsg& from) {
    PlayerLoginMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PlayerLoginMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PlayerLoginMsg";
  }
  protected:
  explicit PlayerLoginMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsernameFieldNumber = 2,
    kUserPassFieldNumber = 3,
    kMsgTypeFieldNumber = 1,
  };
  // string Username = 2;
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // string UserPass = 3;
  void clear_userpass();
  const std::string& userpass() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_userpass(ArgT0&& arg0, ArgT... args);
  std::string* mutable_userpass();
  PROTOBUF_NODISCARD std::string* release_userpass();
  void set_allocated_userpass(std::string* userpass);
  private:
  const std::string& _internal_userpass() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_userpass(const std::string& value);
  std::string* _internal_mutable_userpass();
  public:

  // int32 msgType = 1;
  void clear_msgtype();
  int32_t msgtype() const;
  void set_msgtype(int32_t value);
  private:
  int32_t _internal_msgtype() const;
  void _internal_set_msgtype(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:PlayerLoginMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr userpass_;
    int32_t msgtype_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_2eproto;
};
// -------------------------------------------------------------------

class ServerRespondMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ServerRespondMsg) */ {
 public:
  inline ServerRespondMsg() : ServerRespondMsg(nullptr) {}
  ~ServerRespondMsg() override;
  explicit PROTOBUF_CONSTEXPR ServerRespondMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ServerRespondMsg(const ServerRespondMsg& from);
  ServerRespondMsg(ServerRespondMsg&& from) noexcept
    : ServerRespondMsg() {
    *this = ::std::move(from);
  }

  inline ServerRespondMsg& operator=(const ServerRespondMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerRespondMsg& operator=(ServerRespondMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ServerRespondMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const ServerRespondMsg* internal_default_instance() {
    return reinterpret_cast<const ServerRespondMsg*>(
               &_ServerRespondMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ServerRespondMsg& a, ServerRespondMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerRespondMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerRespondMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ServerRespondMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ServerRespondMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ServerRespondMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ServerRespondMsg& from) {
    ServerRespondMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerRespondMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ServerRespondMsg";
  }
  protected:
  explicit ServerRespondMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 3,
    kRvFieldNumber = 1,
    kMsgTypeFieldNumber = 2,
  };
  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // bool rv = 1;
  void clear_rv();
  bool rv() const;
  void set_rv(bool value);
  private:
  bool _internal_rv() const;
  void _internal_set_rv(bool value);
  public:

  // int32 msgType = 2;
  void clear_msgtype();
  int32_t msgtype() const;
  void set_msgtype(int32_t value);
  private:
  int32_t _internal_msgtype() const;
  void _internal_set_msgtype(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ServerRespondMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    bool rv_;
    int32_t msgtype_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_msg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PlayerLoginMsg

// int32 msgType = 1;
inline void PlayerLoginMsg::clear_msgtype() {
  _impl_.msgtype_ = 0;
}
inline int32_t PlayerLoginMsg::_internal_msgtype() const {
  return _impl_.msgtype_;
}
inline int32_t PlayerLoginMsg::msgtype() const {
  // @@protoc_insertion_point(field_get:PlayerLoginMsg.msgType)
  return _internal_msgtype();
}
inline void PlayerLoginMsg::_internal_set_msgtype(int32_t value) {
  
  _impl_.msgtype_ = value;
}
inline void PlayerLoginMsg::set_msgtype(int32_t value) {
  _internal_set_msgtype(value);
  // @@protoc_insertion_point(field_set:PlayerLoginMsg.msgType)
}

// string Username = 2;
inline void PlayerLoginMsg::clear_username() {
  _impl_.username_.ClearToEmpty();
}
inline const std::string& PlayerLoginMsg::username() const {
  // @@protoc_insertion_point(field_get:PlayerLoginMsg.Username)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlayerLoginMsg::set_username(ArgT0&& arg0, ArgT... args) {
 
 _impl_.username_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PlayerLoginMsg.Username)
}
inline std::string* PlayerLoginMsg::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:PlayerLoginMsg.Username)
  return _s;
}
inline const std::string& PlayerLoginMsg::_internal_username() const {
  return _impl_.username_.Get();
}
inline void PlayerLoginMsg::_internal_set_username(const std::string& value) {
  
  _impl_.username_.Set(value, GetArenaForAllocation());
}
inline std::string* PlayerLoginMsg::_internal_mutable_username() {
  
  return _impl_.username_.Mutable(GetArenaForAllocation());
}
inline std::string* PlayerLoginMsg::release_username() {
  // @@protoc_insertion_point(field_release:PlayerLoginMsg.Username)
  return _impl_.username_.Release();
}
inline void PlayerLoginMsg::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    
  } else {
    
  }
  _impl_.username_.SetAllocated(username, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.username_.IsDefault()) {
    _impl_.username_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PlayerLoginMsg.Username)
}

// string UserPass = 3;
inline void PlayerLoginMsg::clear_userpass() {
  _impl_.userpass_.ClearToEmpty();
}
inline const std::string& PlayerLoginMsg::userpass() const {
  // @@protoc_insertion_point(field_get:PlayerLoginMsg.UserPass)
  return _internal_userpass();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PlayerLoginMsg::set_userpass(ArgT0&& arg0, ArgT... args) {
 
 _impl_.userpass_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:PlayerLoginMsg.UserPass)
}
inline std::string* PlayerLoginMsg::mutable_userpass() {
  std::string* _s = _internal_mutable_userpass();
  // @@protoc_insertion_point(field_mutable:PlayerLoginMsg.UserPass)
  return _s;
}
inline const std::string& PlayerLoginMsg::_internal_userpass() const {
  return _impl_.userpass_.Get();
}
inline void PlayerLoginMsg::_internal_set_userpass(const std::string& value) {
  
  _impl_.userpass_.Set(value, GetArenaForAllocation());
}
inline std::string* PlayerLoginMsg::_internal_mutable_userpass() {
  
  return _impl_.userpass_.Mutable(GetArenaForAllocation());
}
inline std::string* PlayerLoginMsg::release_userpass() {
  // @@protoc_insertion_point(field_release:PlayerLoginMsg.UserPass)
  return _impl_.userpass_.Release();
}
inline void PlayerLoginMsg::set_allocated_userpass(std::string* userpass) {
  if (userpass != nullptr) {
    
  } else {
    
  }
  _impl_.userpass_.SetAllocated(userpass, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.userpass_.IsDefault()) {
    _impl_.userpass_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:PlayerLoginMsg.UserPass)
}

// -------------------------------------------------------------------

// ServerRespondMsg

// bool rv = 1;
inline void ServerRespondMsg::clear_rv() {
  _impl_.rv_ = false;
}
inline bool ServerRespondMsg::_internal_rv() const {
  return _impl_.rv_;
}
inline bool ServerRespondMsg::rv() const {
  // @@protoc_insertion_point(field_get:ServerRespondMsg.rv)
  return _internal_rv();
}
inline void ServerRespondMsg::_internal_set_rv(bool value) {
  
  _impl_.rv_ = value;
}
inline void ServerRespondMsg::set_rv(bool value) {
  _internal_set_rv(value);
  // @@protoc_insertion_point(field_set:ServerRespondMsg.rv)
}

// int32 msgType = 2;
inline void ServerRespondMsg::clear_msgtype() {
  _impl_.msgtype_ = 0;
}
inline int32_t ServerRespondMsg::_internal_msgtype() const {
  return _impl_.msgtype_;
}
inline int32_t ServerRespondMsg::msgtype() const {
  // @@protoc_insertion_point(field_get:ServerRespondMsg.msgType)
  return _internal_msgtype();
}
inline void ServerRespondMsg::_internal_set_msgtype(int32_t value) {
  
  _impl_.msgtype_ = value;
}
inline void ServerRespondMsg::set_msgtype(int32_t value) {
  _internal_set_msgtype(value);
  // @@protoc_insertion_point(field_set:ServerRespondMsg.msgType)
}

// bytes data = 3;
inline void ServerRespondMsg::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& ServerRespondMsg::data() const {
  // @@protoc_insertion_point(field_get:ServerRespondMsg.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ServerRespondMsg::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ServerRespondMsg.data)
}
inline std::string* ServerRespondMsg::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:ServerRespondMsg.data)
  return _s;
}
inline const std::string& ServerRespondMsg::_internal_data() const {
  return _impl_.data_.Get();
}
inline void ServerRespondMsg::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* ServerRespondMsg::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* ServerRespondMsg::release_data() {
  // @@protoc_insertion_point(field_release:ServerRespondMsg.data)
  return _impl_.data_.Release();
}
inline void ServerRespondMsg::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ServerRespondMsg.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_msg_2eproto
