//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 GreenLegend.rc 使用
//
#define IDD_GREENLEGEND_DIALOG          102
#define IDD_PlayTabPage1                103
#define IDD_PlayTabPage2                104
#define IDR_MAINFRAME                   128
#define IDD_TabPAGE1                    130
#define IDD_TabPAGE2                    131
#define IDD_TabPAGE3                    132
#define IDD_TabPAGE4                    133
#define IDD_TabPAGE5                    134
#define IDB_PNG1                        140
#define IDC_TAB1                        1000
#define IDC_TAB2                        1001
#define IDC_PlayerInfoLIST              1002
#define IDC_EDIT_Log                    1004
#define IDC_CKB_NoBlueBlack             1005
#define IDC_EDIT_RedDrug                1006
#define IDC_EDIT_BlueDrug               1007
#define IDC_CKB_NoRedBlack              1008
#define IDC_CKB_BackReel                1009
#define IDC_CKB_BackResolve             1010
#define IDC_CKB_NoMasterRound           1011
#define IDC_EDIT_BackReel               1012
#define IDC_CKB_SaveGoods               1013
#define IDC_CKB_RedFewRand              1014
#define IDC_CKB_Poliphili               1015
#define IDC_CKB_SnowRope                1016
#define IDC_EDIT_NoMasterTime           1017
#define IDC_EDIT_BackStone              1018
#define IDC_CKB_RedFewScreenshot        1021
#define IDC_EDIT_NoMasterRound          1023
#define IDC_CKB_SaveDrug                1024
#define IDC_CKB_EquipmentBack           1025
#define IDC_EDIT_EquipmentBack          1026
#define IDC_CKB_ReturnWait              1027
#define IDC_EDIT_ReturnWait             1028
#define IDC_CKB_EnterMapRand            1029
#define IDC_EDIT_Black                  1030
#define IDC_CKB_BlackRand               1031
#define IDC_COMBO_HookMap               1032
#define IDC_COMBO_MapOrder              1033
#define IDC_CKB_BlackBack               1034
#define IDC_COMBO_EverydayTask          1036
#define IDC_BTN_AddTask                 1037
#define IDC_BTN_AddFlowPath             1039
#define IDC_LIST_FlowPath               1041
#define IDC_CHECK_Green                 1042
#define IDC_CHECK_173                   1043
#define IDC_EDIT_GamePath               1044
#define IDC_EDIT_Account                1045
#define IDC_CKB_Psychedelic             1046
#define IDC_CKB_Nightmare               1047
#define IDC_EDIT_Times                  1048
#define IDC_CKB_NoMasterTime            1049
#define IDC_CKB_BackpackNumb            1050
#define IDC_CKB_BackStone               1051
#define IDC_CKB_Connect                 1052
#define IDC_CKB_Connect2                1053
#define IDC_CKB_CloseTeam               1053
#define IDC_CKB_CureRope                1054
#define IDC_EDIT_Return                 1055
#define IDC_EDIT_SnowRope               1056
#define IDC_EDIT_CureRope               1057
#define IDC_CKC_Rand                    1058
#define IDC_CKB_RedPoison               1058
#define IDC_EDIT_Map2                   1059
#define IDC_CKB_GreenPoison             1059
#define IDC_CKB_AutoLogn                1060
#define IDC_CKB_Order                   1061
#define IDC_CKB_Amulet                  1062
#define IDC_EDIT_Amulet                 1063
#define IDC_CKB_AutoDefend              1064
#define IDC_BTN_END                     1065
#define IDC_CMB_Pattern                 1065
#define IDC_EDIT_Rand                   1066
#define IDC_COMBO2                      1068
#define IDC_CHECK1                      1069
#define IDC_EDIT1                       1070
#define IDC_EDIT2                       1071
#define IDC_CKB_Hide                    1072
#define IDC_EDIT3                       1072
#define IDC_EDIT_Time                   1073
#define IDC_CKB_Fitxy                   1074
#define IDC_EDIT_X_Y                    1075
#define IDC_BTN_SaveConfig              1076
#define IDC_EDIT_X_Y2                   1076
#define IDC_CMB_Area                    1077
#define IDC_CMB_Config                  1078
#define IDC_EDIT_WaitTime               1080
#define IDC_CKB_Fire                    1081
#define IDC_EDIT_Fire                   1082
#define IDC_CKB_MoreOpen                1083
#define IDC_CKB_BindMoney               1084
#define IDC_EDIT_BindMoney              1085
#define IDC_CKB_                        1086
#define IDC_CKB_Fit                     1086
#define IDC_CKB_PoisonMonster           1086
#define IDC_EDIT_eFit                   1087
#define IDC_CHECK2                      1088
#define IDC_CKB_Resurgence              1088
#define IDC_EDIT_RepairWater            1119
#define IDC_CKB_RepairWater             1120
#define IDC_CKB_RandStone               1121
#define IDC_EDIT_RandStone              1122
#define IDC_CKB_BackRecycle             1123
#define IDC_EDIT_BackpackNumb           1124
#define IDC_EDIT_Dungeon                1125
#define IDC_CKB_Dungeon                 1126
#define IDC_BTN_Start                   1151
#define IDC_BTN_Start2                  1152
#define IDC_BTN_OpenGame                1153
#define IDC_CKB_RedFewOffline           1219
#define IDC_EDIT_Offline                1220
#define IDC_EDIT_Screenshot             1222
#define IDC_CKB_RedFewReturn            1253
#define IDC_EDIT_Map                    1319
#define IDC_EDIT_PassWord               1320
#define IDC_EDIT_RedPoison              1321
#define IDC_EDIT_GreenPoison            1322

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1089
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
